version: '3.8'

services:
    prod-app:
        container_name: daggle-prod-app
        build:
            context: .
            dockerfile: Docker/Dockerfile
        environment:
            - MODE=prod
        ports:
            - "80:8080"
        depends_on:
            prod-db:
                condition: service_healthy
        networks:
            - app-prod-network
    prod-db:
        container_name: daggle-prod-db
        image: postgres:14
        restart: always
        environment:
            - POSTGRES_USER=daggle
            - POSTGRES_PASSWORD=abc123
            - POSTGRES_DB=daggle_prod
        ports:
            - "5433:5432"
        volumes:
            - db-prod-data:/var/lib/postgresql/data
            - ./Docker/init.prod.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-prod-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U daggle -d daggle_prod"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
  db-prod-data:

networks:
  app-prod-network:
